#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceASM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	public partial class BankDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDoiTac(DoiTac instance);
    partial void UpdateDoiTac(DoiTac instance);
    partial void DeleteDoiTac(DoiTac instance);
    partial void InsertGiaoDich(GiaoDich instance);
    partial void UpdateGiaoDich(GiaoDich instance);
    partial void DeleteGiaoDich(GiaoDich instance);
    #endregion
		
		public BankDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BankConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BankDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DoiTac> DoiTacs
		{
			get
			{
				return this.GetTable<DoiTac>();
			}
		}
		
		public System.Data.Linq.Table<GiaoDich> GiaoDiches
		{
			get
			{
				return this.GetTable<GiaoDich>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _Pin;
		
		private decimal _SoDu;
		
		private EntitySet<GiaoDich> _GiaoDiches;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnSoDuChanging(decimal value);
    partial void OnSoDuChanged();
    #endregion
		
		public KhachHang()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDu")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public decimal SoDu
		{
			get
			{
				return this._SoDu;
			}
			set
			{
				if ((this._SoDu != value))
				{
					this.OnSoDuChanging(value);
					this.SendPropertyChanging();
					this._SoDu = value;
					this.SendPropertyChanged("SoDu");
					this.OnSoDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_GiaoDich", Storage="_GiaoDiches", ThisKey="MaKH", OtherKey="MaKH")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4, EmitDefaultValue=false)]
		public EntitySet<GiaoDich> GiaoDiches
		{
			get
			{
				if ((this.serializing 
							&& (this._GiaoDiches.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._GiaoDiches;
			}
			set
			{
				this._GiaoDiches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoDiches(GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_GiaoDiches(GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void Initialize()
		{
			this._GiaoDiches = new EntitySet<GiaoDich>(new Action<GiaoDich>(this.attach_GiaoDiches), new Action<GiaoDich>(this.detach_GiaoDiches));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DoiTac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDT;
		
		private string _MatKhau;
		
		private decimal _SoDu;
		
		private EntitySet<GiaoDich> _GiaoDiches;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDTChanging(int value);
    partial void OnMaDTChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnSoDuChanging(decimal value);
    partial void OnSoDuChanged();
    #endregion
		
		public DoiTac()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDT", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int MaDT
		{
			get
			{
				return this._MaDT;
			}
			set
			{
				if ((this._MaDT != value))
				{
					this.OnMaDTChanging(value);
					this.SendPropertyChanging();
					this._MaDT = value;
					this.SendPropertyChanged("MaDT");
					this.OnMaDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDu")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public decimal SoDu
		{
			get
			{
				return this._SoDu;
			}
			set
			{
				if ((this._SoDu != value))
				{
					this.OnSoDuChanging(value);
					this.SendPropertyChanging();
					this._SoDu = value;
					this.SendPropertyChanged("SoDu");
					this.OnSoDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoiTac_GiaoDich", Storage="_GiaoDiches", ThisKey="MaDT", OtherKey="MaDT")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4, EmitDefaultValue=false)]
		public EntitySet<GiaoDich> GiaoDiches
		{
			get
			{
				if ((this.serializing 
							&& (this._GiaoDiches.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._GiaoDiches;
			}
			set
			{
				this._GiaoDiches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoDiches(GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.DoiTac = this;
		}
		
		private void detach_GiaoDiches(GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.DoiTac = null;
		}
		
		private void Initialize()
		{
			this._GiaoDiches = new EntitySet<GiaoDich>(new Action<GiaoDich>(this.attach_GiaoDiches), new Action<GiaoDich>(this.detach_GiaoDiches));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class GiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGD;
		
		private int _MaDT;
		
		private int _MaKH;
		
		private decimal _SoTien;
		
		private decimal _PhiGD;
		
		private System.DateTime _ThoiGian;
		
		private string _TenGD;
		
		private EntityRef<DoiTac> _DoiTac;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGDChanging(string value);
    partial void OnMaGDChanged();
    partial void OnMaDTChanging(int value);
    partial void OnMaDTChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnSoTienChanging(decimal value);
    partial void OnSoTienChanged();
    partial void OnPhiGDChanging(decimal value);
    partial void OnPhiGDChanged();
    partial void OnThoiGianChanging(System.DateTime value);
    partial void OnThoiGianChanged();
    partial void OnTenGDChanging(string value);
    partial void OnTenGDChanged();
    #endregion
		
		public GiaoDich()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					this.OnMaGDChanging(value);
					this.SendPropertyChanging();
					this._MaGD = value;
					this.SendPropertyChanged("MaGD");
					this.OnMaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDT")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int MaDT
		{
			get
			{
				return this._MaDT;
			}
			set
			{
				if ((this._MaDT != value))
				{
					if (this._DoiTac.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDTChanging(value);
					this.SendPropertyChanging();
					this._MaDT = value;
					this.SendPropertyChanged("MaDT");
					this.OnMaDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public decimal SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiGD")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public decimal PhiGD
		{
			get
			{
				return this._PhiGD;
			}
			set
			{
				if ((this._PhiGD != value))
				{
					this.OnPhiGDChanging(value);
					this.SendPropertyChanging();
					this._PhiGD = value;
					this.SendPropertyChanged("PhiGD");
					this.OnPhiGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.DateTime ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGD", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string TenGD
		{
			get
			{
				return this._TenGD;
			}
			set
			{
				if ((this._TenGD != value))
				{
					this.OnTenGDChanging(value);
					this.SendPropertyChanging();
					this._TenGD = value;
					this.SendPropertyChanged("TenGD");
					this.OnTenGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoiTac_GiaoDich", Storage="_DoiTac", ThisKey="MaDT", OtherKey="MaDT", IsForeignKey=true)]
		public DoiTac DoiTac
		{
			get
			{
				return this._DoiTac.Entity;
			}
			set
			{
				DoiTac previousValue = this._DoiTac.Entity;
				if (((previousValue != value) 
							|| (this._DoiTac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoiTac.Entity = null;
						previousValue.GiaoDiches.Remove(this);
					}
					this._DoiTac.Entity = value;
					if ((value != null))
					{
						value.GiaoDiches.Add(this);
						this._MaDT = value.MaDT;
					}
					else
					{
						this._MaDT = default(int);
					}
					this.SendPropertyChanged("DoiTac");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_GiaoDich", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.GiaoDiches.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.GiaoDiches.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._DoiTac = default(EntityRef<DoiTac>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
