//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebASM.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoiTac", Namespace="http://schemas.datacontract.org/2004/07/WebServiceASM")]
    [System.SerializableAttribute()]
    public partial class DoiTac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SoDuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebASM.ServiceReference1.GiaoDich[] GiaoDichesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDT {
            get {
                return this.MaDTField;
            }
            set {
                if ((this.MaDTField.Equals(value) != true)) {
                    this.MaDTField = value;
                    this.RaisePropertyChanged("MaDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SoDu {
            get {
                return this.SoDuField;
            }
            set {
                if ((this.SoDuField.Equals(value) != true)) {
                    this.SoDuField = value;
                    this.RaisePropertyChanged("SoDu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebASM.ServiceReference1.GiaoDich[] GiaoDiches {
            get {
                return this.GiaoDichesField;
            }
            set {
                if ((object.ReferenceEquals(this.GiaoDichesField, value) != true)) {
                    this.GiaoDichesField = value;
                    this.RaisePropertyChanged("GiaoDiches");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GiaoDich", Namespace="http://schemas.datacontract.org/2004/07/WebServiceASM")]
    [System.SerializableAttribute()]
    public partial class GiaoDich : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaGDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SoTienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PhiGDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ThoiGianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaGD {
            get {
                return this.MaGDField;
            }
            set {
                if ((object.ReferenceEquals(this.MaGDField, value) != true)) {
                    this.MaGDField = value;
                    this.RaisePropertyChanged("MaGD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MaDT {
            get {
                return this.MaDTField;
            }
            set {
                if ((this.MaDTField.Equals(value) != true)) {
                    this.MaDTField = value;
                    this.RaisePropertyChanged("MaDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal SoTien {
            get {
                return this.SoTienField;
            }
            set {
                if ((this.SoTienField.Equals(value) != true)) {
                    this.SoTienField = value;
                    this.RaisePropertyChanged("SoTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal PhiGD {
            get {
                return this.PhiGDField;
            }
            set {
                if ((this.PhiGDField.Equals(value) != true)) {
                    this.PhiGDField = value;
                    this.RaisePropertyChanged("PhiGD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime ThoiGian {
            get {
                return this.ThoiGianField;
            }
            set {
                if ((this.ThoiGianField.Equals(value) != true)) {
                    this.ThoiGianField = value;
                    this.RaisePropertyChanged("ThoiGian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string TenGD {
            get {
                return this.TenGDField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGDField, value) != true)) {
                    this.TenGDField = value;
                    this.RaisePropertyChanged("TenGD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://schemas.datacontract.org/2004/07/WebServiceASM")]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SoDuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebASM.ServiceReference1.GiaoDich[] GiaoDichesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SoDu {
            get {
                return this.SoDuField;
            }
            set {
                if ((this.SoDuField.Equals(value) != true)) {
                    this.SoDuField = value;
                    this.RaisePropertyChanged("SoDu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebASM.ServiceReference1.GiaoDich[] GiaoDiches {
            get {
                return this.GiaoDichesField;
            }
            set {
                if ((object.ReferenceEquals(this.GiaoDichesField, value) != true)) {
                    this.GiaoDichesField = value;
                    this.RaisePropertyChanged("GiaoDiches");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBankService")]
    public interface IBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/ThanhToan", ReplyAction="http://tempuri.org/IBankService/ThanhToanResponse")]
        bool ThanhToan(WebASM.ServiceReference1.DoiTac dt, WebASM.ServiceReference1.KhachHang kh, decimal soTien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/ThanhToan", ReplyAction="http://tempuri.org/IBankService/ThanhToanResponse")]
        System.Threading.Tasks.Task<bool> ThanhToanAsync(WebASM.ServiceReference1.DoiTac dt, WebASM.ServiceReference1.KhachHang kh, decimal soTien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/LSKH", ReplyAction="http://tempuri.org/IBankService/LSKHResponse")]
        WebASM.ServiceReference1.GiaoDich[] LSKH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/LSKH", ReplyAction="http://tempuri.org/IBankService/LSKHResponse")]
        System.Threading.Tasks.Task<WebASM.ServiceReference1.GiaoDich[]> LSKHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/LSDT", ReplyAction="http://tempuri.org/IBankService/LSDTResponse")]
        WebASM.ServiceReference1.GiaoDich[] LSDT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/LSDT", ReplyAction="http://tempuri.org/IBankService/LSDTResponse")]
        System.Threading.Tasks.Task<WebASM.ServiceReference1.GiaoDich[]> LSDTAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceChannel : WebASM.ServiceReference1.IBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<WebASM.ServiceReference1.IBankService>, WebASM.ServiceReference1.IBankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ThanhToan(WebASM.ServiceReference1.DoiTac dt, WebASM.ServiceReference1.KhachHang kh, decimal soTien) {
            return base.Channel.ThanhToan(dt, kh, soTien);
        }
        
        public System.Threading.Tasks.Task<bool> ThanhToanAsync(WebASM.ServiceReference1.DoiTac dt, WebASM.ServiceReference1.KhachHang kh, decimal soTien) {
            return base.Channel.ThanhToanAsync(dt, kh, soTien);
        }
        
        public WebASM.ServiceReference1.GiaoDich[] LSKH() {
            return base.Channel.LSKH();
        }
        
        public System.Threading.Tasks.Task<WebASM.ServiceReference1.GiaoDich[]> LSKHAsync() {
            return base.Channel.LSKHAsync();
        }
        
        public WebASM.ServiceReference1.GiaoDich[] LSDT() {
            return base.Channel.LSDT();
        }
        
        public System.Threading.Tasks.Task<WebASM.ServiceReference1.GiaoDich[]> LSDTAsync() {
            return base.Channel.LSDTAsync();
        }
    }
}
